# Generated by Django 4.0.2 on 2022-02-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='genre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='wordname',
            field=models.CharField(max_length=30),
        ),
    ]
